(define tax 0.065)
(define runningTotal 0)
(define currentItem 0)
(define input 0)
(define total 0)
(define total_taxes 0)
(define (roundOff z n)
  (let ((power (expt 10 n)))
    (/ (round (* power z)) power)))

(define (pos runningTotal condition)(

    (+ runningTotal condition)
    (if(eq? condition -1)
        (begin
            (display "\n\nSubtotal: $")
            (display (roundOff runningTotal 2))
            (display "\nTax: $")
            (let ((total_taxes(* runningTotal tax)))
                (display (roundOff total_taxes 2) ))
            (display "\nTotal: $")
            (let ((total_taxes(* runningTotal tax)))
                (let ((total(+ runningTotal total_taxes)))
                    (display (roundOff total 2))))
            (display "\n\n")
            (exit)
        )
        (begin
            (if(eq? condition 0)
                (begin
                    (let ((greeting(display "\nScheme Point-of-Sale\nStart transaction (exit with -1)\n\nEnter a value: $")))
                        (+ greeting (let ((input(read)))((pos (+ condition runningTotal) input)))))
                )
                (begin
                    (display "Enter a value: $")
                    (let ((input(read)))((pos (+ condition runningTotal) input)))
                )
                )
        )    
    )
    )
)